### ISSUE TITLE
tweaked tp2

### ISSUE THREAD

**Issue by IceLancerSR** [burner1024/bg2-tweaks-and-tricks#1]
Hey there.
i randomly stumbled upon ur git saw the code and decided to make little change.
accept it or not.up to you.
what i did was just tweaked tp2 so it can actually be used in front of mod folder.
Resulting in mod files sticking together in one folder and not being tossed all over the place making a mess.
you can also again use weidu for exe install
[setup-tweaks-and-tricks.zip](https://github.com/burner1024/bg2-tweaks-and-tricks/files/216359/setup-tweaks-and-tricks.zip)

**Comment by burner1024** [comment]
Sorry, I don't quite understand what this change is supposed to do, but it certainly does not do that.

There is no mess, anyway.

**Comment by IceLancerSR** [comment]
oh well
